# Generated by Django 4.2.11 on 2024-04-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceiptHub', '0003_receipt_html_datatable_receipt_upload_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='file_displayname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='file_uuid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
