# Generated by Django 4.2.11 on 2024-04-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceiptHub', '0004_receipt_file_displayname_receipt_file_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='file_fullpath',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
