# Generated by Django 4.2.11 on 2024-04-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceiptHub', '0005_receipt_file_fullpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
