# Generated by Django 4.2.11 on 2024-04-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceiptHub', '0007_remove_receipt_id_alter_receipt_file_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='total_amount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
