# Generated by Django 4.2.11 on 2024-04-14 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReceiptHub', '0009_alter_receipt_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='uploaded_file',
        ),
    ]
