# Generated by Django 5.0.4 on 2024-04-15 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReceiptHub', '0010_remove_receipt_uploaded_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
