# Generated by Django 4.2.11 on 2024-04-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceiptHub', '0011_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='creator_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
