# Generated by Django 4.2.11 on 2024-04-15 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReceiptHub', '0013_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
