# Generated by Django 4.2.11 on 2024-04-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceiptHub', '0016_delete_myuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='creator_uuid',
        ),
        migrations.AddField(
            model_name='receipt',
            name='creator_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
